branches:
- id: branch1
  lan_subnet: 192.168.1.0/24
  link_ip_branch: 172.16.1.2/30
  link_ip_hq: 172.16.1.1/30
  name: Branch-Alpha
  namespace: ns_branch1
  veth_local: veth_b1
  veth_peer: veth_b1_hq
  vpn_ip: 10.10.10.2
- id: branch2
  lan_subnet: 192.168.2.0/24
  link_ip_branch: 172.16.2.2/30
  link_ip_hq: 172.16.2.1/30
  name: Branch-Beta
  namespace: ns_branch2
  veth_local: veth_b2
  veth_peer: veth_b2_hq
  vpn_ip: 10.10.10.3
- id: branch3
  lan_subnet: 192.168.3.0/24
  link_ip_branch: 172.16.3.2/30
  link_ip_hq: 172.16.3.1/30
  name: Branch-Gamma
  namespace: ns_branch3
  veth_local: veth_b3
  veth_peer: veth_b3_hq
  vpn_ip: 10.10.10.4
- id: branch4
  lan_subnet: 192.168.4.0/24
  link_ip_branch: 172.16.4.2/30
  link_ip_hq: 172.16.4.1/30
  name: Branch-Delta
  namespace: ns_branch4
  veth_local: veth_branch4
  veth_peer: veth_branch4_hq
  vpn_ip: 10.10.10.5
hq:
  allowed_services:
  - 192.168.0.10:443
  - 192.168.0.20:514
  - 192.168.0.30:123
  lan_subnet: 192.168.0.0/24
  name: HQ
  namespace: ns_hq
  vpn_ip: 10.10.10.1
  vpn_listen_port: 51820
  wg_interface: wg0
