[Interface]
PrivateKey = WIR1GnLdLxP3a4PqtHhXBo4qVRn2GxmxXioH0D0BVXg=
Address = 10.10.10.3/24

[Peer]
PublicKey = frzBfM6pRX2NXBaGYymhIHVXq4x0lahDa4W7UjMPhVU=
Endpoint = 172.16.2.1:51820
AllowedIPs = 10.10.10.1/32, 192.168.0.0/24
PersistentKeepalive = 25
