[Interface]
PrivateKey = 4DftQ3ivC9tl/AeAbmxWdq8JP7ld6uwdXrrmnvmn/kI=
Address = 10.10.10.4/24

[Peer]
PublicKey = frzBfM6pRX2NXBaGYymhIHVXq4x0lahDa4W7UjMPhVU=
Endpoint = 172.16.3.1:51820
AllowedIPs = 10.10.10.1/32, 192.168.0.0/24
PersistentKeepalive = 25
