[Interface]
PrivateKey = +MbXp3Th4GT1EWz5lpMFP93/atfIg3/ao3Zq/Eki+n8=
Address = 10.10.10.2/24

[Peer]
PublicKey = frzBfM6pRX2NXBaGYymhIHVXq4x0lahDa4W7UjMPhVU=
Endpoint = 172.16.1.1:51820
AllowedIPs = 10.10.10.1/32, 192.168.0.0/24
PersistentKeepalive = 25
