[Interface]
PrivateKey = kErQ+Ac+f+I9GozWhmEtqlgWhJmkoKY7lv91AemdS3E=
Address = 10.10.10.1/24
ListenPort = 51820

[Peer]
# Branch-Alpha
PublicKey = EbHya5N1vsArV7V1Cu8wOkqU820or20/fjTuQHXAdQs=
AllowedIPs = 10.10.10.2/32

[Peer]
# Branch-Beta
PublicKey = C9UrbTGQ7aS2cg6Sk3GF4kYjNBalYyK/WYj804UBA0s=
AllowedIPs = 10.10.10.3/32

[Peer]
# Branch-Gamma
PublicKey = hLfQEZZP+0Y0U6mIn3H3/Nc0SwVC8Ys7TnNG5LFAenQ=
AllowedIPs = 10.10.10.4/32

[Peer]
# Branch-Delta
PublicKey = /MzEABPWOUxl0KqxAmCGws+m8OmgXIrTVZAV2PwTwQQ=
AllowedIPs = 10.10.10.5/32
